[env:arduino_uno_r4_wifi]
platform  = renesas-ra
board     = uno_r4_wifi
framework = arduino
monitor_speed = 115200

[env:arduino_uno_r4_minima]
platform  = renesas-ra
board     = uno_r4_minima
framework = arduino
monitor_speed = 115200
